steps:
  - id: Install
    timeout: 600s
    name: node
    entrypoint: yarn
    args: ['workspace', 'clapy-root', 'install']
  - id: Migrate
    timeout: 40s
    name: node
    entrypoint: yarn
    args: ['${_MIGRATE_SCRIPT}']
    env:
      - 'HASURA_GRAPHQL_ADMIN_SECRET=$_HASURA_GRAPHQL_ADMIN_SECRET'
options:
  substitutionOption: MUST_MATCH
substitutions:
  _MIGRATE_SCRIPT: 'migrate:prod'
  _HASURA_GRAPHQL_ADMIN_SECRET: 'secret'
tags:
  - 'db-${_DEPLOYMENT_TYPE}'
